"""Add career matching fields

Revision ID: 5301b8222bf0
Revises: 9215d31a9d65
Create Date: 2025-03-29 17:40:57.330780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5301b8222bf0'
down_revision = '9215d31a9d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('date_earned',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('animations_enabled')
        batch_op.drop_column('theme')
        batch_op.drop_column('mobile_number')
        batch_op.drop_column('dob')
        batch_op.drop_column('profile_image')
        batch_op.drop_column('bio')
        batch_op.drop_column('pin_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_code', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('mobile_number', sa.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('animations_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.alter_column('date_earned',
               existing_type=sa.DATETIME(),
               nullable=False)

    op.create_table('university',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
