"""Add test score columns to User model

Revision ID: 495578d21774
Revises: bda0f610b4e4
Create Date: 2025-04-11 10:32:23.271588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495578d21774'
down_revision = 'bda0f610b4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aptitude_scores', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('personality_scores', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('skill_gap_scores', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('aptitude_completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('personality_completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('skill_gap_completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('skill_gap_completed_at')
        batch_op.drop_column('personality_completed_at')
        batch_op.drop_column('aptitude_completed_at')
        batch_op.drop_column('skill_gap_scores')
        batch_op.drop_column('personality_scores')
        batch_op.drop_column('aptitude_scores')

    # ### end Alembic commands ###
